# Generated by Django 4.2 on 2025-03-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicant_google_drive_url_jobposting_custom_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='google_drive_url',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='custom_title',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
