# Generated by Django 4.2 on 2025-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_applicant_google_drive_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
